### Test 1: Register a new Student
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Test Student",
  "email": "student5@example.com",
  "password": "password123",
  "role": "STUDENT"
}

### Test 2: Login User (Get Token)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "saurabhpandey8908@gmail.com",
  "password": "brandNewPassword123"
}
### Test : Login User (Get Token)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "student5@example.com",
  "password": "password123"
}

### Test 3 : Register User
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Saurabh Pandey",
  "email": "saurabhpandey8908@gmail.com",
  "password": "password963",
  "role": "ADMIN"
}

### Test 4: Change Password
POST http://localhost:8080/api/users/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzYXVyYWJocGFuZGV5ODkwOEBnbWFpbC5jb20iLCJpYXQiOjE3NjcwMjI4MjUsImV4cCI6MTc2NzEwOTIyNX0.mbMmDPbVzr9t5LLElI8gv_osm3v99bhr5K-V20zFEeg2zmxPhLsD5cGKt3x2Akkp

{
  "currentPassword": "newPassword789",
  "newPassword": "newPassword7890",
  "confirmationPassword": "newPassword7890"
}

### Test 5: Forgot Password
POST http://localhost:8080/api/users/forgot-password
Content-Type: application/json

{
  "email": "saurabhpandey8908@gmail.com"
}

### Test 6: Reset Password (Using Token)
POST http://localhost:8080/api/users/reset-password
Content-Type: application/json

{
  "token": "f876e779-c80a-4599-97eb-71fb5010579c",
  "newPassword": "brandNewPassword123",
  "confirmPassword": "brandNewPassword123"
}

### Test 7: Upload Material (Multipart)
POST http://localhost:8080/api/materials/upload
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzYXVyYWJocGFuZGV5ODkwOEBnbWFpbC5jb20iLCJpYXQiOjE3NjcwMjI4MjUsImV4cCI6MTc2NzEwOTIyNX0.mbMmDPbVzr9t5LLElI8gv_osm3v99bhr5K-V20zFEeg2zmxPhLsD5cGKt3x2Akkp
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="title"

Java Basics - Chapter 1
--WebAppBoundary
Content-Disposition: form-data; name="description"

Introduction to Java syntax and loops.
--WebAppBoundary
Content-Disposition: form-data; name="subject"

Java Programming
--WebAppBoundary
Content-Disposition: form-data; name="type"

NOTE
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.pdf"

< ./test.pdf
--WebAppBoundary--

### Test 8 : Get list of pending notes
GET http://localhost:8080/api/materials/pending
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzYXVyYWJocGFuZGV5ODkwOEBnbWFpbC5jb20iLCJpYXQiOjE3NjcwMzM1NzQsImV4cCI6MTc2NzExOTk3NH0.s-Eb2nAM9lQQWFf31jFGBZ7S6O3rits0xTTxOrxakhJS8koMAiNTELvyGPBXn73K
Content-Type: application/json


### Test 9 :  Approve a Material
PUT http://localhost:8080/api/materials/35/approve
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzYXVyYWJocGFuZGV5ODkwOEBnbWFpbC5jb20iLCJpYXQiOjE3NjcwMzM1NzQsImV4cCI6MTc2NzExOTk3NH0.s-Eb2nAM9lQQWFf31jFGBZ7S6O3rits0xTTxOrxakhJS8koMAiNTELvyGPBXn73K
Content-Type: application/json

###